apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alb-tester.yaml
  - aws-load-balancer-controller/service-account.yaml
  - aws-load-balancer-controller/cert-manager.yaml
  - aws-load-balancer-controller/controller.yaml